/**
 * نظام الأيقونات — سطح استيراد واحد فوق lucide-react.
 * استورد الأيقونات من هنا في بقية المشروع بدل lucide-react مباشرة،
 * حتى يسهل استبدال المكتبة لاحقًا من مكان واحد فقط.
 *
 * Icon system — a single import surface over lucide-react.
 * Import icons from here elsewhere in the project instead of importing
 * lucide-react directly, so swapping the library later only touches
 * one file.
 */
export {
  Sun,
  Moon,
  Monitor,
  Globe,
  Menu,
  X,
  Search,
  User,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Check,
  Loader2,
  Eye,
  EyeOff,
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  Info,
  XCircle,
  Home,
  MoreHorizontal,
  Circle,
  BookOpen,
  ScrollText,
  BookOpenCheck,
  MessageCircleQuestion,
  Newspaper,
  GraduationCap,
  Library,
  Users,
  Sparkles,
  ArrowLeft,
  ArrowRight,
  Languages,
  BookMarked,
  PlayCircle,
  SlidersHorizontal,
  Clock,
  TrendingUp,
  SearchX,
  Headphones,
  Video,
  FileText,
  Landmark,
  ArrowUpLeft,
  Copy,
  Share2,
  Bookmark,
  BookmarkCheck,
  Play,
  Pause,
  Link2,
  MessageSquare,
  Clock3,
  ListTree,
  MessageCircle,
  User2,
  Award,
  FileDown,
  Lock,
  CircleDot,
  ListChecks,
  LayoutDashboard,
  Bell,
  Activity,
  AlertOctagon,
  Pencil,
  Trash2,
  ArrowUpDown,
  Plus,
  Settings,
  Shield,
  ShieldCheck,
  Globe2,
  Mail,
  Database,
  Plug,
  BarChart3,
  FileWarning,
  Image as ImageIcon,
  Quote,
  Table as TableIcon,
  Heading,
  FileCode,
  Save,
  UploadCloud,
  Folder,
  LayoutGrid,
  Rows3,
  Music,
  RotateCcw,
  FileX,
  UserCheck,
  Cpu,
} from "lucide-react";
