import type { Role } from "@prisma/client";

export const PERMISSIONS = {
  VIEW_PUBLIC_CONTENT: "VIEW_PUBLIC_CONTENT",
  VIEW_MEMBER_CONTENT: "VIEW_MEMBER_CONTENT",
  ENROLL_IN_COURSES: "ENROLL_IN_COURSES",
  ACCESS_STUDENT_AREA: "ACCESS_STUDENT_AREA",
  MANAGE_OWN_COURSES: "MANAGE_OWN_COURSES",
  REVIEW_SCHOLARLY_CONTENT: "REVIEW_SCHOLARLY_CONTENT",
  MODERATE_COMMUNITY: "MODERATE_COMMUNITY",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_CONTENT: "MANAGE_CONTENT",
  MANAGE_SYSTEM: "MANAGE_SYSTEM",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  VISITOR: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
  ],

  MEMBER: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
    PERMISSIONS.VIEW_MEMBER_CONTENT,
  ],

  STUDENT: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
    PERMISSIONS.VIEW_MEMBER_CONTENT,
    PERMISSIONS.ENROLL_IN_COURSES,
    PERMISSIONS.ACCESS_STUDENT_AREA,
  ],

  TEACHER: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
    PERMISSIONS.VIEW_MEMBER_CONTENT,
    PERMISSIONS.ENROLL_IN_COURSES,
    PERMISSIONS.ACCESS_STUDENT_AREA,
    PERMISSIONS.MANAGE_OWN_COURSES,
  ],

  SCHOLAR_REVIEWER: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
    PERMISSIONS.VIEW_MEMBER_CONTENT,
    PERMISSIONS.REVIEW_SCHOLARLY_CONTENT,
  ],

  COMMUNITY_MODERATOR: [
    PERMISSIONS.VIEW_PUBLIC_CONTENT,
    PERMISSIONS.VIEW_MEMBER_CONTENT,
    PERMISSIONS.MODERATE_COMMUNITY,
  ],

  ADMIN: Object.values(PERMISSIONS),
};